---
title: "Completeness of annotations"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(bugphyzzAnalyses)
library(bugphyzz)
library(dplyr)
library(purrr)
library(ggplot2)
library(tibble)
library(magrittr)
library(ComplexHeatmap)
```


Estimate completeness

$$\text{Completeness (%)} = \frac{\text{N taxa in BugPhyzz}}{\text{N taxa in reference database (e.g., NCBI)}} * 100$$

# Import all bugphyzz datasets

```{r, message=FALSE}
bp <- physiologies() %>% 
    map(as_tibble)
```

# Import reference dataset

In this case, I'll use the taxonomy of the NCBI as reference. Only
the taxa belonging to Archaea or Bacteria will be imported.

```{r, message=FALSE}
ncbi_taxonomy_table <- get_ncbi_taxonomy()
glimpse(ncbi_taxonomy_table)
```


# Number of taxa in the NCBI database per rank

```{r}
valid_ranks <- c(
    'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'species',
    'strain'
)

counts <- ncbi_taxonomy_table %>% 
    filter(rank %in% valid_ranks) %>% 
    split(f = factor(.$rank)) %>% 
    map_int(~ length(pull(.x, rank)))

counts %>% 
    as.data.frame() %>% 
    rownames_to_column(var = 'rank') %>% 
    as_tibble() %>% 
    set_colnames(c('rank', 'n')) %>% 
    mutate(rank = factor(rank, levels = valid_ranks)) %>% 
    ggplot(aes(rank, n)) +
    geom_col() +
    geom_label(aes(label = n)) +
    ggtitle(
        'Number of taxa per rank in the NCBI taxonomy database'
    )
```

# Completeness in bugphyzz (before phylogenetic/taxonomic propagation)

```{r}
counts_bp <- map(bp, ~ {
    attr_counts <- get_attr_counts(.x)
    attr_counts / counts[names(attr_counts)] * 100
}) %>% 
    bind_rows(.id = 'attribute') %>% 
    column_to_rownames(var = 'attribute') %>% 
    as.data.frame() %>% 
    as.matrix() 
counts_bp[is.na(counts_bp)] <- 0
order_cols <- valid_ranks[valid_ranks %in% colnames(counts_bp)]
counts_bp <- counts_bp[, order_cols]
```

Draw heatmap

```{r, fig.height=7, fig.width=5}
col_fun <- circlize::colorRamp2(c(0, 0.0001, 100), c("white", "lightblue", "darkblue"))
Heatmap(
    counts_bp, 
    col = col_fun,
    name = '%',
    row_title = 'Attributes',
    column_title = 'Ranks',
    cluster_columns = FALSE
)
```



