---
title: "Enrichment with dbBact approach"
subtitle: "Concatenate then filter even signatures"
output:
    html_document:
        toc: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Setup

```{r setup, message=FALSE}
library(bugphyzzAnalyses)
library(bugsigdbr)
library(bugphyzz)
library(purrr)
library(dplyr)
library(stringr)
library(tidyr)
library(ggplot2)
library(ComplexHeatmap)

## Variables
body_sites <- c(
    skin = "skin", vagina = "vagina", mouth = "mouth", feces = "feces"
)
ranks <- c(genus = "genus", species = "species")
directions <- c(increased = "increased", decreased = "decreased")

score_opt <- "counts"

```

# Data

Import bugphyzz:

```{r, warning=FALSE, message=FALSE}
bp <- importBugphyzz()

## Genus signatures
bpSigs_g <- map(bp, ~ {
    makeSignatures(
        dat = .x,  tax_id_type = "NCBI_ID", tax_level = "genus",
        min_size = 10
    )
}) |> 
    list_flatten(name_spec = "{inner}") |> 
    discard(is.null)

## Species signatures
bpSigs_s <- map(bp, ~ {
    makeSignatures(
        dat = .x,  tax_id_type = "NCBI_ID", tax_level = "species",
        min_size = 10
    )
}) |> 
    list_flatten(name_spec = "{inner}") |> 
    discard(is.null)
```

Import BugSigDB:

```{r}
bsdb_doi <- "10.5281/zenodo.10627578" # v1.2.1
bsdb <- importBugSigDB(version = bsdb_doi)
bsdb <- bsdb |> 
    filter(`Host species` == "Homo sapiens") |> 
    filter(`Abundance in Group 1` %in% c("increased", "decreased")) |>
    filter(!is.na(`Body site`)) |> 
    filter(`Study design` == "case-control" )
dim(bsdb)
```

Subset by body site (using ontologies):

```{r}
uberon <- getOntology(onto = "uberon")
bsdb_subsets_by_bodysite <- vector("list", length(body_sites))
names(bsdb_subsets_by_bodysite) <- body_sites
for (i in seq_along(bsdb_subsets_by_bodysite)) {
    if (body_sites[i] == "skin") { ## Didn't find an ontology for skin
        bsdb_subsets_by_bodysite[[i]] <- bsdb |> 
            filter(grepl(body_sites[i], `Body site`, ignore.case = TRUE))
    } else {
        bsdb_subsets_by_bodysite[[i]] <- subsetByOntology(
            bsdb, column = "Body site", term = body_sites[i], ontology = uberon 
        )
    }
}
```

Create concatenated signatures:

```{r}
catSigs_g <- map(bsdb_subsets_by_bodysite, ~ {
    getCatSignatures(.x, "genus", min_size = 5)
}) |> 
    discard(~ !length(.x))
catSigs_s <- map(bsdb_subsets_by_bodysite, ~ {
    getCatSignatures(.x, "species", min_size = 5)
}) |> 
    discard(~ !length(.x))
```

```{r, warning=FALSE}
## There are warnings for the wilcox test
feces_enriched_g <- map2(
    .x = catSigs_g$feces$decreased,
    .y = catSigs_g$feces$increased,
    ~ dbEn2(control = .x, case = .y, term_list = bpSigs_g, opt = score_opt)
) |> 
    discard(is.null)
feces_enriched_s <- map2(
    .x = catSigs_s$feces$decreased,
    .y = catSigs_s$feces$increased,
    ~ dbEn2(control = .x, case = .y, term_list = bpSigs_s, opt = score_opt)
) |> 
    discard(is.null)
mouth_enriched_g <- map2(
    .x = catSigs_g$mouth$decreased,
    .y = catSigs_g$mouth$increased,
    ~ dbEn2(control = .x, case = .y, term_list = bpSigs_g, opt = score_opt)
) |> 
    discard(is.null)
mouth_enriched_s <- map2(
    .x = catSigs_s$mouth$decreased,
    .y = catSigs_s$mouth$increased,
    ~ dbEn2(control = .x, case = .y, term_list = bpSigs_s, opt = score_opt)
) |> 
    discard(is.null)
```


```{r, fig.height=13, fig.width=22}
ht <- dbHt(feces_enriched_s$`Colorectal-cancer`)
```

```{r, fig.height=10, fig.width=15}
ht2 <- dbHt(mouth_enriched_s$`Smoking-behavior`)
```

```{r, fig.width=20, fig.height=13}
dbHt(feces_enriched_g$Obesity)
```






# Session information

```{r}
sessioninfo::session_info()
```
