---
title: "MSEA control vs IBD in cMD for aerophilicity attributes"
output:
  html_document:
    toc: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)
```

```{r packages, message=FALSE}
library(bugphyzz)
library(curatedMetagenomicData)
library(dplyr)
library(EnrichmentBrowser)
```

# Expected result

+ Enrichment of anaerobic bacteria in healthy samples (gut).
+ Enrichment of facultative anaerobic bacteria in IBD samples (gut).

# Data

Use the HMP_2019_bidmdb study in cMD:

```{r import tse, message=FALSE, warning=FALSE}
dataset_name <- "HallAB_2017.relative_abundance"
tse <- curatedMetagenomicData(
    pattern = dataset_name, 
    dryrun = FALSE, rownames = 'NCBI',
    counts = TRUE
)[[1]]
colData(tse)$GROUP <- ifelse(colData(tse)$study_condition == 'control', 0, 1)
tse 
```
# bugphyzz data

```{r bp signatures species}
bp <- importBugphyzz()
bp <- bp |> 
  filter(Attribute_group == 'aerophilicity')
sp_sigs <- getBugphyzzSignatures(
  df = bp, tax.id.type = 'NCBI_ID', tax.level = 'species'
)
```

# DESEQ2 + ORA and GSEA

DA:

```{r}
assay(tse, 'relab_plus_1') <- assay(tse, 'relative_abundance') + 1
deseq <- deAna(
    expr = tse, de.method = 'DESeq2', padj.method = 'BH', 
    assay = 'relab_plus_1'
)
dim(deseq)
```

ORA:

```{r, message=FALSE, warning=FALSE}
deseq_ora <- sbea(
    method = 'ora', se = deseq, gs = sp_sigs, alpha = 0.1, perm = 0,
    padj.method = 'BH', assay = 'relab_plus_1'
)
gsRanking(res = deseq_ora, signif.only = FALSE)
```

GSEA:

```{r, message=FALSE, warning=FALSE}
deseq_gsea <- sbea(
    method = 'gsea', se = deseq, gs = sp_sigs, alpha = 0.1, perm = 0,
    padj.method = 'BH', assay = 'relab_plus_1'
)
gsRanking(res = deseq_gsea, signif.only = FALSE)
```

# edgeR

```{r}
edger <- deAna(
    expr = tse, de.method = 'edgeR', padj.method = 'BH', 
    assay = 'relab_plus_1'
)
```

ORA:

```{r}
edger_ora <- sbea(
    method = 'ora', se = edger, gs = sp_sigs, alpha = 0.1, perm = 0,
    padj.method = 'BH', assay = 'relab_plus_1'
)
gsRanking(edger_ora, signif.only = FALSE)
```

GSEA:

```{r}
edger_gsea <- sbea(
    method = 'gsea', se = edger, gs = sp_sigs, alpha = 0.1, perm = 0,
    padj.method = 'BH', assay = 'relab_plus_1'
)
gsRanking(edger_gsea, signif.only = FALSE)
```

# Session Information

```{r}
sessionInfo()
```
