---
title: "nsti"
output:
    html_document:
        toc: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(bugphyzz)
library(purrr)
library(dplyr)
library(ggplot2)
library(taxPPro)
library(ape)
library(castor)
```

## Import data

```{r, message=FALSE}
bp <- importBugphyzz(version = "devel")
```

## Density plot of NSTI values

```{r, warning=FALSE}
dat <- purrr::map(bp, ~ {
    .x |> 
        filter(Attribute_type == "numeric")
}) |> 
    discard(~ !nrow(.x)) |> 
    purrr::map(~ filter(.x, !is.na(NSTI))) |> 
    discard(~ !nrow(.x)) |> 
    bind_rows()
    
dat |> 
    ggplot(aes(NSTI)) +
    geom_histogram(
        aes(fill = Attribute), color = "black", binwidth = 0.02
    )  +
    facet_wrap(~Attribute) +
    theme_bw() 

```


```{r}
ltp <- ltp()
tr <- ltp$tree
```

```{r}
fts <- find_farthest_tip_pair(tr)
```

```{r}
tip1 <- tr$tip.label[fts$tip1]
tip2 <- tr$tip.label[fts$tip2]
tbl <- tibble(
    tip1 = tip1,
    tip2 = tip2,
    dist = fts$distance
)
tbl
```

```{r}
nsti_ecoli <- getNsti(tr, "Escherichia_coli-_-X80725--_ATCC_11775T_T")
```

```{r}
thr <- 0.2
mins <- dat |> 
    filter(NSTI < thr) |> 
    arrange(NSTI) |> 
    slice_min(order_by = NSTI, n = 10)
mins
```

```{r}
maxs <- dat |> 
    filter(NSTI < thr) |> 
    arrange(NSTI) |> 
    slice_max(order_by = NSTI, n = 10)
maxs
```

A function for converting NSTI into Frequency and then into scores

```{r}
nsti2Freq <- function(x) {
    dplyr::case_when(
        is.na(x) ~ NA,
        x == 0 ~ "always",
        x > 0 & x <= 0.05 ~ "usually",
        x > 0.05 & x <= 0.15 ~ "sometimes",
        x > 0.15 & x <= 0.2 ~ "rarely",
        x > 0.2 ~ "never"
    )
}
    
dat$Frequency <- nsti2Freq(dat$NSTI)
dat$Score <- freq2Scores(dat$Frequency) ## Need freq2Scores2
```

## Session information

```{r}
sessioninfo::session_info()
```
