---
title: "BSEA gingival plaque - MicrobiomeBenchmarkData - 35S"
output:
  html_document:
    toc: true
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE
)
```

```{r packages, message=FALSE, warning=FALSE}
library(bugphyzzAnalyses)
library(MicrobiomeBenchmarkData)
library(bugphyzz)
library(EnrichmentBrowser)
library(mia)
library(dplyr)
```

# Microbiome data

```{r import tse data, message=FALSE}
dat_name <- 'HMP_2012_16S_gingival_V35'
tse <- getBenchmarkData(dat_name, dryrun = FALSE)[[1]]
tse_genus <- splitByRanks(tse)$genus
## Filter taxa with at least 1 abundance in at least 20% of samples
min_n_samples <- round(ncol(tse_genus) * 0.2)
tse_subset <- tse_genus[rowSums(assay(tse_genus) >= 1) >= min_n_samples,]
tse_subset
```
Number of samples per condition

```{r}
table(tse_subset$body_subsite)
```

# bugphyzz signatures

Signatures at the genus level:

```{r bp signatures genus}
bp <- importBugphyzz()
aer <- filter(bp, Attribute_group == 'aerophilicity')
gn_sigs <- getBugphyzzSignatures(
  df = aer, tax.id.type = 'Taxon_name', tax.level = 'genus'
)
```

# Differential abundance

```{r DA - edgeR}
tse_subset$GROUP <- ifelse(
  tse_subset$body_subsite == 'subgingival_plaque', 0, 1
)
edger <- deAna(
    expr = tse_subset, de.method = 'edgeR', padj.method = 'BH', 
    filter.by.expr = FALSE, 
)
```

# Enrichment (GSEA)

```{r}
gsea <- sbea(
  method = 'gsea', se = edger, gs = gn_sigs, perm = 1000, padj.method = 'BH',
  alpha = 0.1
  
)
gsea_tbl <- as.data.frame(gsRanking(gsea, signif.only = FALSE))
arrange(gsea_tbl, PVAL)
```

# Enrichment (ORA)

Enriched in supragingival (up):

```{r}
edger_up <- edger
rowData(edger_up)$ADJ.PVAL <- ifelse(
  rowData(edger_up)$FC < 0, 1, rowData(edger_up)$ADJ.PVAL
)
ora_up <- sbea(
  method = 'ora', se = edger_up, gs = gn_sigs, alpha = 0.1, perm = 0, 
  padj.method = 'BH'
)
ora_up_df <- as.data.frame(gsRanking(ora_up, signif.only = FALSE))
arrange(ora_up_df, PVAL)
```

Enriched in subgingival (down):

```{r}
edger_down <- edger
rowData(edger_down)$ADJ.PVAL <- ifelse(
  rowData(edger_down)$FC > 0, 1, rowData(edger_down)$ADJ.PVAL
)
ora_down <- sbea(
  method = 'ora', se = edger_down, gs = gn_sigs, alpha = 0.1, perm = 0, 
  padj.method = 'BH'
)
ora_down_df <- as.data.frame(gsRanking(ora_down, signif.only = FALSE))
arrange(ora_down_df, PVAL) |> 
  DT::datatable(
    filter = 'top',
    options = list(
      dom = '<"top"B>lfrtip',
      buttons = list('copy', 'print'),
      iDisplayLength = 10,
      keys = TRUE,
      autoWidth = TRUE
    )
  )
```

# Session information

```{r session info}
sessioninfo::session_info()
```

