---
title: "Tree summaries"
---

```{r options, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Packages

```{r setup, message=FALSE}
library(data.tree)
library(bugphyzz)
library(taxPPro)
library(purrr)
library(tidyr)
library(dplyr)
library(ggplot2)
```

## Import data

Import bugphyzz and NCBI tree (taxPPro):

```{r get child taxa for species, message=FALSE}
data('tree_list')
ncbiTree <- as.Node(tree_list)
bp <- importBugphyzz()
```

## Number of child taxa per species

```{r}
childTaxaSp <- ncbiTree$Get(
    attribute = 'children',
    filterFun = function(node) grepl('^s__', node$name)
)
number_children_sp <- map_int(childTaxaSp, ~ {
    sum(!is.na(.x))
})
nChildDF <- data.frame(
    name = names(number_children_sp),
    n_child = unname(number_children_sp) 
) |> 
    mutate(
        cat = case_when(
            n_child == 0 ~ '0',
            n_child > 0 & n_child <= 20 ~ '1-20',
            n_child > 20 ~ '>20'
        )
    )

count(nChildDF, cat)
```

> Less than 6000 species have children (strains). Some of these, like
Staphilococcus aureous have a lot (up to 4628).


```{r}
ncbi_nodes <- ncbiTree$Get(
    attribute = 'name',
    filterFun = function(node) node$name != 'ArcBac',
    simplify = TRUE
) |>
    names() |> 
    {\(y) sub('^\\w__', '', y)}()
```



```{r}
aer <- filter(bp, Attribute_group == 'aerophilicity') |> 
    mutate(input = ifelse(NCBI_ID %in% ncbi_nodes, TRUE, FALSE)) |> 
    mutate(Attribute_source = ifelse(Evidence == 'inh', NA, Attribute_source))
```

```{r}
aer |> 
    filter(!is.na(Attribute_source)) |> 
    count(Rank, Attribute_source, input) |> 
    arrange(Rank, Attribute_source, input)
```

## Genus

```{r}
aerGn <- filter(bp, Attribute_group == 'aerophilicity', Rank == 'genus')
genera <- ncbiTree$Get(
    attribute = 'name',
    filterFun = function(node) grepl('g__', node$name),
    simplify = TRUE
) |> 
    unname() |> 
    {\(y) sub('g__', '', y)}()

g <- count(aerGn, Evidence)
ids <- filter(aer, Evidence %in% c('exp', 'igc', 'tas', 'nas')) |> 
    pull(NCBI_ID)
g2 <- data.frame(Evidence = 'input', n = sum(ids %in% genera))
rbind(g, g2)
```


## Species

```{r}
aerSp <- filter(bp, Attribute_group == 'aerophilicity', Rank == 'species')

species <- ncbiTree$Get(
    attribute = 'name',
    filterFun = function(node) grepl('s__', node$name),
    simplify = TRUE
) |> 
    unname() |> 
    {\(y) sub('s__', '', y)}()

s <- count(aerSp, Evidence)
sp_ids <- filter(aer, Evidence %in% c('exp', 'igc', 'tas', 'nas')) |> 
    pull(NCBI_ID)
s2 <- data.frame(Evidence = 'input', n = sum(sp_ids %in% species))
rbind(s, s2)
```


## Strain

```{r}
aerSt <- filter(bp, Attribute_group == 'aerophilicity', Rank == 'strain')
strains <- ncbiTree$Get(
    attribute = 'name',
    filterFun = function(node) grepl('t__', node$name),
    simplify = TRUE
) |> 
    unname() |> 
    {\(y) sub('t__', '', y)}()

st <- count(aerSt, Evidence)
st_ids <- filter(aer, Evidence %in% c('exp', 'igc', 'tas', 'nas')) |> 
    pull(NCBI_ID)
st2 <- data.frame(Evidence = 'input', n = sum(st_ids %in% strains))
rbind(st, st2)
```

## Session information

```{r session info}
sessioninfo::session_info()
```

